name: Build and Deploy to aliyun
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Deploy
        uses: easingthemes/ssh-deploy@v4.0.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_PRIMARY_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: 22
          TARGET: /usr/project_demo/next-app
